-- 1. Buat Tabel STO Mapping
CREATE TABLE IF NOT EXISTS sto_mapping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kode_sto TEXT NOT NULL UNIQUE,
    nama_wilayah TEXT NOT NULL,
    witel TEXT DEFAULT 'LAINNYA',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Masukkan Data Awal (Seed Data)
-- Witel Purwokerto & Sekitarnya
INSERT OR IGNORE INTO sto_mapping (kode_sto, nama_wilayah, witel) VALUES 
('PWT', 'PURWOKERTO', 'PURWOKERTO'),
('BYM', 'PURWOKERTO', 'PURWOKERTO'),
('CLO', 'PURWOKERTO', 'PURWOKERTO'),
('KRY', 'PURWOKERTO', 'PURWOKERTO'),
('SDJ', 'PURWOKERTO', 'PURWOKERTO'),
('SUK', 'SOKARAJA', 'PURWOKERTO'),
('AJB', 'AJIBARANG', 'PURWOKERTO'),
('BBL', 'BUMIAYU', 'PURWOKERTO'),
('BJR', 'BANJARNEGARA', 'PURWOKERTO'),
('BNA', 'BANJARNEGARA', 'PURWOKERTO'),
('PBG', 'PURBALINGGA', 'PURWOKERTO'),
('BBT', 'PURBALINGGA', 'PURWOKERTO'),
('CIL', 'CILACAP', 'PURWOKERTO'),
('CLC', 'CILACAP', 'PURWOKERTO'),
('MAN', 'CILACAP', 'PURWOKERTO'),
('MAO', 'CILACAP', 'PURWOKERTO'),
('KJA', 'KROYA', 'PURWOKERTO'),
('MJN', 'MAJENANG', 'PURWOKERTO'),
('SDA', 'SIDAREJA', 'PURWOKERTO'),
('WOS', 'WONOSOBO', 'PURWOKERTO'),
('WNS', 'WONOSOBO', 'PURWOKERTO');

-- Witel Magelang & Sekitarnya
INSERT OR IGNORE INTO sto_mapping (kode_sto, nama_wilayah, witel) VALUES 
('MAG', 'MAGELANG', 'MAGELANG'),
('PRN', 'MAGELANG', 'MAGELANG'),
('KTW', 'MAGELANG', 'MAGELANG'),
('SWT', 'MAGELANG', 'MAGELANG'),
('GOM', 'MAGELANG', 'MAGELANG'),
('MTY', 'MAGELANG', 'MAGELANG'),
('TEM', 'MAGELANG', 'MAGELANG'),
('TMG', 'TEMANGGUNG', 'MAGELANG'),
('MUN', 'MAGELANG', 'MAGELANG'),
('MTP', 'MUNTILAN', 'MAGELANG'),
('KTA', 'MAGELANG', 'MAGELANG'),
('PWJ', 'PURWOREJO', 'MAGELANG'),
('PWR', 'PURWOREJO', 'MAGELANG'),
('KEB', 'KEBUMEN', 'MAGELANG');

-- Wilayah Jawa Tengah & Lainnya
INSERT OR IGNORE INTO sto_mapping (kode_sto, nama_wilayah, witel) VALUES 
('PKL', 'PEKALONGAN', 'LAINNYA'),
('BTG', 'BATANG', 'LAINNYA'),
('TGL', 'TEGAL', 'LAINNYA'),
('SLW', 'SLAWI', 'LAINNYA'),
('BRB', 'BREBES', 'LAINNYA'),
('BBS', 'BREBES', 'LAINNYA'),
('KTG', 'KETANGGUNGAN', 'LAINNYA'),
('PML', 'PEMALANG', 'LAINNYA'),
('SMG', 'SEMARANG', 'LAINNYA'),
('SLO', 'SOLO', 'LAINNYA'),
('KLT', 'KLATEN', 'LAINNYA'),
('BYL', 'BOYOLALI', 'LAINNYA'),
('SKH', 'SUKOHARJO', 'LAINNYA'),
('WNG', 'WONOGIRI', 'LAINNYA'),
('KRN', 'KARANGANYAR', 'LAINNYA'),
('SRG', 'SRAGEN', 'LAINNYA'),
('KDS', 'KUDUS', 'LAINNYA'),
('PTI', 'PATI', 'LAINNYA'),
('JPR', 'JEPARA', 'LAINNYA'),
('RBG', 'REMBANG', 'LAINNYA'),
('BLA', 'BLORA', 'LAINNYA'),
('CPT', 'CEPU', 'LAINNYA'),
('SLT', 'SALATIGA', 'LAINNYA'),
('UNG', 'UNGARAN', 'LAINNYA'),
('AMB', 'AMBARAWA', 'LAINNYA'),
('KDL', 'KENDAL', 'LAINNYA'),
('WLR', 'WELERI', 'LAINNYA'),
('PWD', 'PURWODADI', 'LAINNYA');

-- Kota Besar Lainnya
INSERT OR IGNORE INTO sto_mapping (kode_sto, nama_wilayah, witel) VALUES 
('JKT', 'JAKARTA', 'LAINNYA'),
('BDG', 'BANDUNG', 'LAINNYA'),
('SBY', 'SURABAYA', 'LAINNYA'),
('YGY', 'YOGYAKARTA', 'LAINNYA');

